version: 2.1

executors:
  machine-executor:
    machine:
      image: node:latest

jobs:
  build:
    executor: machine-executor
    steps:
      - run:
          name: Build Project
          command: |
            echo "Building the project..."

  deploy:
    executor: machine-executor
    steps:
      - run:
          name: Deploy 
          command: |
            cd /opt/lampp/htdocs/mutillidae && git pull origin main && sudo /opt/lampp/lampp restart

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
